language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
script:
  - npm test
env:
  global:
    - secure: pUPjwZ6T+a8irxSNYiXgniViD+VKq/FL1ayJxa+9FhONm05P2tptp53W43a6c40bGrLbEmprwN9bm2IXahP5tOTlOLTj3U8eU2Nel9/EHJF13SpSEDIQSObb/TXIbnbjjwsLsP2hegkOsF/cQk7tFQw7tDwCIeOSp+bJAm2LIM4=
    - secure: ICS6YWwYmJ6058wC+LbjbxSvBzlQGU+jIL1WEIkPCY1nEl7zNJN8UI08qIXbT7JKzEmb9EIrD6cHlF17Jrgex7MxCj8miMiEOB3F15GvMfCTGcCV+vCjvihdP7Vord+tkh7jzQuuOFU9qT4bKTZ+3Jj9XT9fSxpBw8Qch4Dacow=
